export const UPDATE_POST = 'UPDATE_POST';
export const SET_PROFILES = 'SET_PROFILES';
export const SET_PROFILE = 'SET_PROFILE';

export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const UPDATE_FIRSTNAME = 'UPDATE_FIRSTNAME';
export const UPDATE_LASTNAME = 'UPDATE_LASTNAME';
export const UPDATE_AGE = 'UPDATE_AGE';
export const UPDATE_CITY = 'UPDATE_CITY';
export const UPDATE_SKILLS = 'UPDATE_SKILLS';
export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';

export const PROFILE_DELETED = 'PROFILE_DELETED';
export const PROFILE_STATUS = 'PROFILE_STATUS';
export const PROFILE_EDITED = 'PROFILE_EDITED';
export const PROFILE_CLEARED = 'PROFILE_CLEARED';
