export const CURRENT_INPUT_VALUE = 'CURRENT_INPUT_VALUE';
export const LOAD_PROFILES = 'LOAD_PROFILES';

export const CURRENT_FORM_FIRST_NAME = 'CURRENT_FORM_FIRST_NAME';
export const CURRENT_FORM_LAST_NAME = 'CURRENT_FORM_LAST_NAME';
export const CURRENT_FORM_AGE = 'CURRENT_FORM_AGE';
export const CURRENT_FORM_CITY = 'CURRENT_FORM_CITY';
export const CURRENT_FORM_SKILLS = 'CURRENT_FORM_SKILLS';
export const CURRENT_FORM_FAVORITES = 'CURRENT_FORM_FAVORITES';
export const CURRENT_FORM_IMG = 'CURRENT_FORM_IMG';
export const CURRENT_FORM_FILTER = 'CURRENT_FORM_FILTER';

export const CURRENT_EDIT_FIRST_NAME = 'CURRENT_EDIT_FIRST_NAME';
export const CURRENT_EDIT_LAST_NAME = 'CURRENT_EDIT_LAST_NAME';
export const CURRENT_EDIT_AGE = 'CURRENT_EDIT_AGE';
export const CURRENT_EDIT_CITY = 'CURRENT_EDIT_CITY';
export const CURRENT_EDIT_SKILLS = 'CURRENT_EDIT_SKILLS';
export const CURRENT_EDIT_FAVORITES = 'CURRENT_EDIT_FAVORITES';
export const CURRENT_EDIT_IMG = 'CURRENT_EDIT_IMG';
export const CURRENT_EDIT_FILTER = 'CURRENT_EDIT_FILTER';

export const CREATE_NEW_PROFILE = 'CREATE_NEW_PROFILE';
export const PROFILE_TO_EDIT = 'PROFILE_TO_EDIT';
export const CURRENT_INPUT_FIND = 'CURRENT_INPUT_FIND';
export const PROFILE_CREATED = 'PROFILE_CREATED';
export const PROFILE_EDITED = 'PROFILE_EDITED';
